/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceModeRouteImport } from './routes/voice-mode'
import { Route as TrustedCircleRouteImport } from './routes/trusted-circle'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScamShieldRouteImport } from './routes/scam-shield'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GovernmentSchemesRouteImport } from './routes/government-schemes'
import { Route as FutureSelfRouteImport } from './routes/future-self'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinancialCalendarRouteImport } from './routes/financial-calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingReadyRouteImport } from './routes/onboarding.ready'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as OnboardingIncomeRouteImport } from './routes/onboarding.income'
import { Route as OnboardingConcernRouteImport } from './routes/onboarding.concern'
import { Route as OnboardingCashflowRouteImport } from './routes/onboarding.cashflow'
import { Route as OnboardingAccessibilityRouteImport } from './routes/onboarding.accessibility'

const VoiceModeRoute = VoiceModeRouteImport.update({
  id: '/voice-mode',
  path: '/voice-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedCircleRoute = TrustedCircleRouteImport.update({
  id: '/trusted-circle',
  path: '/trusted-circle',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScamShieldRoute = ScamShieldRouteImport.update({
  id: '/scam-shield',
  path: '/scam-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentSchemesRoute = GovernmentSchemesRouteImport.update({
  id: '/government-schemes',
  path: '/government-schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureSelfRoute = FutureSelfRouteImport.update({
  id: '/future-self',
  path: '/future-self',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialCalendarRoute = FinancialCalendarRouteImport.update({
  id: '/financial-calendar',
  path: '/financial-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingReadyRoute = OnboardingReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIncomeRoute = OnboardingIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConcernRoute = OnboardingConcernRouteImport.update({
  id: '/concern',
  path: '/concern',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCashflowRoute = OnboardingCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAccessibilityRoute = OnboardingAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/financial-calendar': typeof FinancialCalendarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/trusted-circle': typeof TrustedCircleRoute
  '/voice-mode': typeof VoiceModeRoute
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/cashflow': typeof OnboardingCashflowRoute
  '/onboarding/concern': typeof OnboardingConcernRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/financial-calendar': typeof FinancialCalendarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/trusted-circle': typeof TrustedCircleRoute
  '/voice-mode': typeof VoiceModeRoute
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/cashflow': typeof OnboardingCashflowRoute
  '/onboarding/concern': typeof OnboardingConcernRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/financial-calendar': typeof FinancialCalendarRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/future-self': typeof FutureSelfRoute
  '/government-schemes': typeof GovernmentSchemesRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/scam-shield': typeof ScamShieldRoute
  '/signup': typeof SignupRoute
  '/trusted-circle': typeof TrustedCircleRoute
  '/voice-mode': typeof VoiceModeRoute
  '/onboarding/accessibility': typeof OnboardingAccessibilityRoute
  '/onboarding/cashflow': typeof OnboardingCashflowRoute
  '/onboarding/concern': typeof OnboardingConcernRoute
  '/onboarding/income': typeof OnboardingIncomeRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/ready': typeof OnboardingReadyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/community'
    | '/dashboard'
    | '/financial-calendar'
    | '/forgot-password'
    | '/future-self'
    | '/government-schemes'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/scam-shield'
    | '/signup'
    | '/trusted-circle'
    | '/voice-mode'
    | '/onboarding/accessibility'
    | '/onboarding/cashflow'
    | '/onboarding/concern'
    | '/onboarding/income'
    | '/onboarding/language'
    | '/onboarding/ready'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/community'
    | '/dashboard'
    | '/financial-calendar'
    | '/forgot-password'
    | '/future-self'
    | '/government-schemes'
    | '/impact'
    | '/login'
    | '/scam-shield'
    | '/signup'
    | '/trusted-circle'
    | '/voice-mode'
    | '/onboarding/accessibility'
    | '/onboarding/cashflow'
    | '/onboarding/concern'
    | '/onboarding/income'
    | '/onboarding/language'
    | '/onboarding/ready'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/ai-assistant'
    | '/community'
    | '/dashboard'
    | '/financial-calendar'
    | '/forgot-password'
    | '/future-self'
    | '/government-schemes'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/scam-shield'
    | '/signup'
    | '/trusted-circle'
    | '/voice-mode'
    | '/onboarding/accessibility'
    | '/onboarding/cashflow'
    | '/onboarding/concern'
    | '/onboarding/income'
    | '/onboarding/language'
    | '/onboarding/ready'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AiAssistantRoute: typeof AiAssistantRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  FinancialCalendarRoute: typeof FinancialCalendarRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FutureSelfRoute: typeof FutureSelfRoute
  GovernmentSchemesRoute: typeof GovernmentSchemesRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ScamShieldRoute: typeof ScamShieldRoute
  SignupRoute: typeof SignupRoute
  TrustedCircleRoute: typeof TrustedCircleRoute
  VoiceModeRoute: typeof VoiceModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-mode': {
      id: '/voice-mode'
      path: '/voice-mode'
      fullPath: '/voice-mode'
      preLoaderRoute: typeof VoiceModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-circle': {
      id: '/trusted-circle'
      path: '/trusted-circle'
      fullPath: '/trusted-circle'
      preLoaderRoute: typeof TrustedCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scam-shield': {
      id: '/scam-shield'
      path: '/scam-shield'
      fullPath: '/scam-shield'
      preLoaderRoute: typeof ScamShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government-schemes': {
      id: '/government-schemes'
      path: '/government-schemes'
      fullPath: '/government-schemes'
      preLoaderRoute: typeof GovernmentSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-self': {
      id: '/future-self'
      path: '/future-self'
      fullPath: '/future-self'
      preLoaderRoute: typeof FutureSelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-calendar': {
      id: '/financial-calendar'
      path: '/financial-calendar'
      fullPath: '/financial-calendar'
      preLoaderRoute: typeof FinancialCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/ready': {
      id: '/onboarding/ready'
      path: '/ready'
      fullPath: '/onboarding/ready'
      preLoaderRoute: typeof OnboardingReadyRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/income': {
      id: '/onboarding/income'
      path: '/income'
      fullPath: '/onboarding/income'
      preLoaderRoute: typeof OnboardingIncomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/concern': {
      id: '/onboarding/concern'
      path: '/concern'
      fullPath: '/onboarding/concern'
      preLoaderRoute: typeof OnboardingConcernRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/cashflow': {
      id: '/onboarding/cashflow'
      path: '/cashflow'
      fullPath: '/onboarding/cashflow'
      preLoaderRoute: typeof OnboardingCashflowRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/accessibility': {
      id: '/onboarding/accessibility'
      path: '/accessibility'
      fullPath: '/onboarding/accessibility'
      preLoaderRoute: typeof OnboardingAccessibilityRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingAccessibilityRoute: typeof OnboardingAccessibilityRoute
  OnboardingCashflowRoute: typeof OnboardingCashflowRoute
  OnboardingConcernRoute: typeof OnboardingConcernRoute
  OnboardingIncomeRoute: typeof OnboardingIncomeRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingReadyRoute: typeof OnboardingReadyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAccessibilityRoute: OnboardingAccessibilityRoute,
  OnboardingCashflowRoute: OnboardingCashflowRoute,
  OnboardingConcernRoute: OnboardingConcernRoute,
  OnboardingIncomeRoute: OnboardingIncomeRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingReadyRoute: OnboardingReadyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AiAssistantRoute: AiAssistantRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  FinancialCalendarRoute: FinancialCalendarRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FutureSelfRoute: FutureSelfRoute,
  GovernmentSchemesRoute: GovernmentSchemesRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ScamShieldRoute: ScamShieldRoute,
  SignupRoute: SignupRoute,
  TrustedCircleRoute: TrustedCircleRoute,
  VoiceModeRoute: VoiceModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
